humshaugh_table_tennis_project/humshaugh_table_tennis/urls.py
from django.conf.urls import url
from humshaugh_table_tennis import views

app_name = 'humshaugh_table_tennis'

urlpatterns = [
    url('^$', views.home, name='home'),
    url('^club-nights/$', views.club_nights, name='club_nights'),
    url('^news/(?P<page>\d+)/$', views.news, name='news'),
    url('^contact-us/$', views.contact_us, name='contact_us'),
    url('^rules/$', views.rules, name='rules'),
    url('^rules-full/$', views.rules_full, name='rules_full'),
    url('^location/$', views.location, name='location'),
##    url('^login/$', views.login, name='login'),

]

humshaugh_table_tennis_project/humshaugh_table_tennis_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from humshaugh_table_tennis import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('humshaugh_table_tennis.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

humshaugh_table_tennis_project/humshaugh_table_tennis/models.py
from __future__ import unicode_literals

from django.db import models

class News(models.Model):
    #restrictions
    MAX_TITLE_LENGTH=1000
    MAX_CONTENT_LENGTH=20000

    #fields
    title = models.CharField(max_length=MAX_TITLE_LENGTH)
    content = models.TextField(max_length=MAX_CONTENT_LENGTH)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'News'

    #functions
    def __str__(self):
        return self.title
    def __unicode__(self):
        return self.title

humshaugh_table_tennis_project/humshaugh_table_tennis/forms.py
from django import forms
from humshaugh_table_tennis.models import News

class NewsForm(forms.ModelForm):
    title = forms.CharField(max_length=News.MAX_TITLE_LENGTH, help_text="Header")
    content = forms.CharField(max_length=News.MAX_CONTENT_LENGTH, help_text="Content")

    class Meta:
        model = News
        fields = ('title', 'content')

humshaugh_table_tennis_project/humshaugh_table_tennis/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from humshaugh_table_tennis.models import News
from humshaugh_table_tennis.forms import NewsForm

def home(request):
    return render(request, 'humshaugh_table_tennis/home.html')

def news(request, page):
    context_dict = {}
    page = int(page)
    news_count = News.objects.all().count()

    last_page = (news_count / 10) + 1
    
    if page < 1 or page != 1 and page > last_page:
        return HttpResponseRedirect(reverse('humshaugh_table_tennis:news', args=[1]))
        

    # show ten per page
    # u is upper bound
    # l is lower bound
    u = page * 10
    l = u - 10
    posts = News.objects.order_by('-date')[l:u]

    context_dict['last_page'] = last_page
    context_dict['page'] = page
    context_dict['posts'] = posts
    return render(request, 'humshaugh_table_tennis/news.html', context_dict)


def club_nights(request):
    return render(request, 'humshaugh_table_tennis/club_nights.html')

def contact_us(request):
    return render(request, 'humshaugh_table_tennis/contact_us.html')

def location(request):
    return render(request, 'humshaugh_table_tennis/location.html')

def rules(request):
    return render(request, 'humshaugh_table_tennis/rules.html')

def rules_full(request):
    return render(request, 'humshaugh_table_tennis/rules_full.html')



##def login(request):
##    context_dict = {}
##
##    if request.method == 'POST':
##        # check if username and password are valid
##        username = request.POST.get('username')
##        password = request.POST.get('password')
##
##        user = authenticate(username=username, password=password)
##
##        if user:
##            # check account is not disabled
##            if user.is_active:
##                # login the user and redirect to their profile
##                login(request, user)
##                return HttpResponseRedirect(reverse('humshaugh_table_tennis:manage'))
##
##            # inactive account
##            else:
##                context_dict['errors'] = ['Your account is disabled.']
##                return render(request, 'humshaugh_table_tennis/login.html', context_dict)
##
##        # invalid login details
##        else:
##            print('Invalid login details: {0}, {1}'.format(username, password))
##            context_dict['errors'] = ['Invalid login details']
##            return render(request, 'humshaugh_table_tennis/login.html', context_dict)
##        
##    else:
##        # Not HTTP POST
##        return render(request, 'humshaugh_table_tennis/login.html', context_dict)
##
##

    

humshaugh_table_tennis_project/templates/humshaugh_table_tennis/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
	<link href='http://fonts.googleapis.com/css?family=Goudy+Bookletter+1911' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Raleway:100' rel='stylesheet' type='text/css'>
	<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	<title>
		Humshaugh Table Tennis
		{% block title_block %}
		{% endblock %}
	</title>
</head>

<!-- background="{% static "/images/background.jpg" %}" -->
<body background="{% static '/images/background.jpg' %}">

	<ul id="sidebar">
		<li><a href="{% url 'humshaugh_table_tennis:home' %}">Home</a></li>
		<li><a href="{% url 'humshaugh_table_tennis:club_nights' %}">Club Nights</a></li>
		<li><a href="{% url 'humshaugh_table_tennis:location' %}">Location</a></li>
		<li><a href="{% url 'humshaugh_table_tennis:news' 1 %}">News</a></li>
		<li><a href="{% url 'humshaugh_table_tennis:rules' %}">Rules</a></li>
		<li><a href="{% url 'humshaugh_table_tennis:contact_us' %}">Contact Us</a></li>
	</ul>

	<div class="body_block">
		<h1>Humshaugh Table Tennis Club</h1>
		<h3>Email: <a href="mailto:humshaughtt@gmail.com">humshaughtt@gmail.com</a></h3>
	</div>

	<div>
	{% block body_block %}
	{% endblock %}
	</div>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
	<script src="{% static 'javascript/jquery.js' %}"></script>
</body>
</html>

humshaugh_table_tennis_project/templates/humshaugh_table_tennis/club_nights.html
{% extends 'humshaugh_table_tennis/base.html' %}
<!DOCTYPE html>
{% load staticfiles %}

{% block title_block %}
 - Club Nights
{% endblock %}

{% block body_block %}
<div class="body_block">
	<h2>Club Nights</h2>
	<div class="border-t">
	We play on Thursday evenings between September and May - see calendar.
	</div>
	<div class="border-tb" style="text-align:center;">
		<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showCalendars=0&amp;showTz=0&amp;height=600&amp;wkst=2&amp;bgcolor=%23ffffff&amp;src=humshaughtt%40gmail.com&amp;color=%231B887A&amp;ctz=Europe%2FLondon" width="800" height="600" frameborder="0" scrolling="no"></iframe>
	</div>
</div>
{% endblock %}

humshaugh_table_tennis_project/templates/humshaugh_table_tennis/contact_us.html
{% extends 'humshaugh_table_tennis/base.html' %}
<!DOCTYPE html>
{% load staticfiles %}

{% block title_block %}
 - Contact Us
{% endblock %}

{% block body_block %}
<div class="body_block">
	<h2>Contact Us</h2>
	<div class="border-tb">
	<table id="contact-table">
		<tr>
			<td><big>Contacts/Committee</big></td>
			<td><big>Role</big></td>
			<td><big>Phone</big></td>
		</tr>
		<tr>
			<td>Richard Bullen</td>
			<td>Chair & Competition Secretary</td>
			<td>01434 681603</td>
		</tr>


	</table>
	</div>
</div>
{% endblock %}

humshaugh_table_tennis_project/templates/humshaugh_table_tennis/home.html
{% extends 'humshaugh_table_tennis/base.html' %}
<!DOCTYPE html>
{% load staticfiles %}

{% block title_block %}
 - Home
{% endblock %}

{% block body_block %}
<div class="body_block">
	<h2>Welcome</h2>
	<div class="border-t">
		Humshaugh Table Tennis Club (HTTC) has been formed to encourage and promote this healthy sport at all levels of ages (Over 10 years old) and abilities.
		<br><br>
		Our club meetings are held on most (but not all) Thursdays in Humshaugh Village Hall which is spacious and well lighted making it very suitable for this sport.
		<br><br>
		We are currently seeking new members from Humshaugh and the surrounding Tynedale Towns and Villages.
		<br><br>
		Please come and visit us to see the facilities and decide whether you are interested in joining the club.
		<br><br>
		Chairperson
	</div>
	<div class="border-tb">
		<img id="villagehall" src="{% static 'images/villagehall.jpg' %}" width="570" height="333">
	</div>
</div>
{% endblock %}

humshaugh_table_tennis_project/templates/humshaugh_table_tennis/location.html
{% extends 'humshaugh_table_tennis/base.html' %}
<!DOCTYPE html>
{% load staticfiles %}

{% block title_block %}
 - Location
{% endblock %}

{% block body_block %}
<div class="body_block">
    <h2>Location</h2>
	<div class="border-tb">
		<div id="map" allowTransparency="false"></div>
		<p id="google-maps-link"><a href="https://www.google.com/maps/dir/Current+Location/Humshaugh+Table+Tennis+Club+Humshaugh+NE46+4AD" target="_blank">Get directions</a></p>
		<script>
		  function initMap() {
			var hums = {lat: 55.0359, lng: -2.1267};
			var map = new google.maps.Map(document.getElementById('map'), {
			  zoom: 16,
			  center: hums
			});
			var marker = new google.maps.Marker({
			  position: hums,
			  map: map
			});
		  }
		</script>
		<script async defer
		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDgoGScDQs39l63LWPE56v818AVjwTG3Zw&callback=initMap">
		</script>
	</div>
</div>
{% endblock %}

humshaugh_table_tennis_project/templates/humshaugh_table_tennis/news.html
{% extends 'humshaugh_table_tennis/base.html' %}
<!DOCTYPE html>
{% load staticfiles %}

{% block title_block %}
 - News
{% endblock %}

{% block body_block %}
<div class="multi_body_block" id="news_block_1">
	<h2>News</h2>
	{% if posts %}
		{% for post in posts %}
			<div class="border-t">
				<h4><big>{{ post.title }}</big> - {{ post.date }}</h4>
				{{ post.content|linebreaks }}
			</div>
		{% endfor %}

		<div class="border-tb" style="text-align: center;">
			{% if page > 1 %}
				<a href="{% url 'humshaugh_table_tennis:news' page|add:'-1' %}">previous</a>
				&nbsp;
			{% endif %}

			{% if page > 3 %}
			. . .&nbsp;
			{% endif %}

			{% if page > 2 %}
				<a href="{% url 'humshaugh_table_tennis:news' page|add:'-2' %}">{{ page|add:'-2' }}</a>
				&nbsp;
			{% endif %}

			{% if page > 1 %}
				<a href="{% url 'humshaugh_table_tennis:news' page|add:'-1' %}">{{ page|add:'-1' }}</a>
				&nbsp;
			{% endif %}

			<b>{{ page }}</b>
			&nbsp;

			{% if page < last_page %}
				<a href="{% url 'humshaugh_table_tennis:news' page|add:'1' %}">{{ page|add:'1' }}</a>
				&nbsp;
			{% endif %}

			{% if page < last_page|add:'-1' %}
				<a href="{% url 'humshaugh_table_tennis:news' page|add:'2' %}">{{ page|add:'2' }}</a>
				&nbsp;
			{% endif %}

			{% if page < last_page|add:'-2' %}
			. . .
			&nbsp;
			{% endif %}

			{% if page < last_page %}
				<a href="{% url 'humshaugh_table_tennis:news' page|add:'1' %}">next</a>
			{% endif %}

		</div>

	{% else %}
		<div class="border-tb" style="text-align: center">
			There is no news!
		</div>
	{% endif %}
</div>

<div class="multi_body_block" id="news_block_2">
	<div id="fb-widget">
		<iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fnorthumbriatabletennis%2F&tabs=timeline&width=300&height=700&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=false&appId" width="300" height="550" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="false"></iframe>
	</div>
</div>
{% endblock %}

humshaugh_table_tennis_project/templates/humshaugh_table_tennis/rules.html
{% extends 'humshaugh_table_tennis/base.html' %}
<!DOCTYPE html>
{% load staticfiles %}

{% block title_block %}
 - Rules
{% endblock %}

{% block body_block %}
<div class="body_block">
	<h2>Rules - All you need to know to play a fun game</h2>
	<div class="border-t">
		Sometimes all you want to know are the basic rules to play a friendly match of table tennis. This section is for you. If you want more offical rules, <a href="{% url 'humshaugh_table_tennis:rules_full' %}">click here</a>.
		<br><br>
		In singles, the centre lines serve no purpose, so ignore them.
	</div>
	<div class="border-t">
		<h4>Scoring</h4>

		A match is played best 3 of 5 games (or 4/7 or 5/9). For each game, the first player to reach 11 points wins that game, however a game must be won by at least a two point margin. A point is scored after each ball is put into play (not just when the server wins the point).
		<br><br>
		The edges of the table are part of the legal table surface, but not the sides.
	</div>
	<div class="border-t">
		<h4>Flow of the Match</h4>

		Each player serves two points in a row and then switch server. However, if a score of 10-10 is reached in any game, then each server serves only one point and then the server is switched. After each game, the players switch side of the table. In the final game (ie 5th game), the players switch side again after either player reaches 5 points.
	</div>
	<div class="border-t">
		<h4>Legal Service</h4>

		The ball must rest on an open hand palm. Then it must be tossed up at least 6 inches and struck so the ball first bounces on the server's side and then the opponent's side. If the serve is legal except that it touches the net, it is called a let serve. Let serves are not scored and the serve is played again.
	</div>
	<div class="border-tb">
		<h4>Equipment</h4>

		The bat should have a red and a black side. The ball should be either orange or white and 40 mm in size. The table should be 2.74 meters long, 1.525m wide, and 0.76m high.
	</div>
</div>
{% endblock %}

humshaugh_table_tennis_project/templates/humshaugh_table_tennis/rules_full.html
{% extends 'humshaugh_table_tennis/base.html' %}
<!DOCTYPE html>
{% load staticfiles %}

{% block title_block %}
 - Rules (full)
{% endblock %}

{% block body_block %}
<div class="body_block">


<h2>ENGLISH TABLE TENNIS ASSOCIATION LIMITEDTHE ETTA APPROVED LAWS OF TABLE TENNIS 2009-10</h2>
<div class="border-t">
	<h4>2.1 THE TABLE</h4>

	2.1.1 The upper surface of the table, known as the playing surface, shall be rectangular, 2.74m long and 1.525m wide, and shall lie in a horizontal plane 76cm above the floor.
	<br><br>
	2.1.2 The playing surface shall not include the vertical sides of the table-top.
	<br><br>
	2.1.3 The playing surface may be of any material and shall yield a uniform bounce of about 23cm when a standard ball is dropped on to it from a height of 30cm.
	<br><br>
	2.1.4 The playing surface shall be uniformly dark coloured and matt, but with a white side line, 2cm wide, along each 2.74m edge and a white end line, 2cm wide, along each 1.525m edge.
	<br><br>
	2.1.5 The playing surface shall be divided into 2 equal courts by a vertical net running parallel with the end lines, and shall be continuous over the whole area of each court.
	<br><br>
	2.1.6 For doubles, each court shall be divided into 2 equal half-courts by a white centre line, 3mm wide, running parallel with the side lines; the centre line shall be regarded as part of each right half-court.
</div>
<div class="border-t">
	<h4>2.2 THE NET ASSEMBLY</h4>

	2.2.1 The net assembly shall consist of the net, its suspension and the supporting posts, including the clamps attaching them to the table.
	<br><br>
	2.2.2 The net shall be suspended by a cord attached at each end to an upright post 15.25cm high, the outside limits of the post being 15.25cm outside the side line.
	<br><br>
	2.2.3 The top of the net, along its whole length, shall be 15.25cm above the playing surface.
	<br><br>
	2.2.4 The bottom of the net, along its whole length, shall be as close as possible to the playing surface and the ends of the net shall be as close as possible to the supporting posts.
</div>
<div class="border-t">
	<h4>2.3 THE BALL</h4>

	2.3.1 The ball shall be spherical, with a diameter of 40mm.
	<br><br>
	2.3.2 The ball shall weigh 2.7g.
	<br><br>
	2.3.3 The ball shall be made of celluloid or similar plastics material and shall be white or orange, and matt.
	<br><br>
	2.3.4 The ball shall be of a brand and type currently approved by the ITTF. (ETTA Rule 46.8)
</div>
<div class="border-t">
	<h4>2.4 THE RACKET</h4>

	2.4.1 The racket may be of any size, shape or weight but the blade shall be flat and rigid.
	<br><br>
	2.4.2 At least 85% of the blade by thickness shall be of natural wood; an adhesive layer within the blade may be reinforced with fibrous material such as carbon fibre, glass fibre or compressed paper, but shall not be thicker than 7.5% of the total thickness or 0.35mm, whichever is the smaller.
	<br><br>
	2.4.3 A side of the blade used for striking the ball shall be covered with either ordinary pimpled rubber, with pimples outwards having a total thickness including adhesive of not more than 2.0mm, or sandwich rubber, with pimples inwards or outwards, having a total thickness including adhesive of not more than 4.0mm.
	<br><br>
	2.4.3.1 Ordinary pimpled rubber is a single layer of non-cellular rubber, natural or synthetic, with pimples evenly distributed over its surface at a density of not less than 10/cm2 and not more than 30/cm2.
	<br><br>
	2.4.3.2 Sandwich rubber is a single layer of cellular rubber covered with a single outer layer of ordinary pimpled rubber, the thickness of the pimpled rubber not being more than 2mm.
	<br><br>
	2.4.4 The covering material shall extend up to but not beyond the limits of the blade, except that the part nearest the handle and gripped by the fingers may be left uncovered or covered with any material.
	<br><br>
	2.4.5 The blade, any layer within the blade and any layer of covering material or adhesive on a side used for striking the ball shall be continuous and of even thickness.
	<br><br>
	2.4.6 The surface of the covering material on a side of the blade, or of a side of the blade if it is left uncovered, shall be matt, bright red on one side and black on the other.
	<br><br>
	2.4.7 The racket covering shall be used without any chemical, physical or other treatment.
</div>
<div class="border-t">
	<h4>A GAME</h4>

	2.11.1 A game shall be won by the player or pair first scoring 11 points unless both players or pairs score 10 points, when the game shall be won by the first player or pair subsequently gaining a lead of 2 points.
</div>
<div class="border-t">
	<h4>2.12 A MATCH</h4>

	2.12.1 A match shall consist of the best of any odd number of games.
</div>
<div class="border-t">
	<h4>2.13 THE ORDER OF SERVING, RECEIVING AND ENDS</h4>

	2.13.1 The right to choose the initial order of serving, receiving and ends shall be decided by lot and the winner may choose to serve or to receive first or to start at a particular end.
	<br><br>
	2.13.2 When one player or pair has chosen to serve or to receive first or to start at a particular end, the other player or pair shall have the other choice.
	<br><br>
	2.13.3 After each 2 points have been scored the receiving player or pair shall become the serving player or pair and so on until the end of the game, unless both players or pairs score 10 points or the expedite system is in operation, when the sequences of serving and receiving shall be the same but each player shall serve for only 1 point in turn.
	<br><br>
	2.13.4 In each game of a doubles match, the pair having the right to serve first shall choose which of them will do so and in the first game of a match the receiving pair shall decide which of them will receive first; in subsequent games of the match, the first server having been chosen, the first receiver shall be the player who served to him in the preceding game.
	<br><br>
	2.13.5 In doubles, at each change of service the previous receiver shall become the server and the partner of the previous server shall become the receiver.
	<br><br>
	2.13.6 The player or pair serving first in a game shall receive first in the next game of the match and in the last possible game of a doubles match the pair due to receive next shall change their order of receiving when first one pair scores 5 points.
	<br><br>
	2.13.7 The player or pair starting at one end in a game shall start at the other end in the next game of the match and in the last possible game of a match the players or pairs shall change ends when first one player or pair scores 5 points.
</div>
<div class="border-t">
	<h4>2.14 OUT OF ORDER OF SERVING, RECEIVING OR ENDS</h4>

	2.14.1 If a player serves or receives out of turn, play shall be interrupted by the umpire as soon as the error is discovered and shall resume with those players serving and receiving who should be server and receiver respectively at the score that has been reached, according to the sequence established at the beginning of the match and, in doubles, to the order of serving chosen by the pair having the right to serve first in the game during which the error is discovered.
	<br><br>
	2.14.2 If the players have not changed ends when they should have done so, play shall be interrupted by the umpire as soon as the error is discovered and shall resume with the players at the ends at which they should be at the score that has been reached, according to the sequence established at the start of the match.
	<br><br>
	2.14.3 In any circumstances, all points scored before the discovery of an error shall be reckoned.
</div>
<div class="border-tb">
	<h4>2.15 THE EXPEDITE SYSTEM</h4>

	2.15.1 Except where both players or pairs have scored at least 9 points, the expedite system shall come into operation if a game is unfinished after 10 minutes’ play or at any earlier time at the request of both players or pairs.
	<br><br>
	2.15.1.1 If the ball is in play when the time limit is reached, play shall be interrupted by the umpire and shall resume with service by the player who served in the rally that was interrupted.
	<br><br>
	2.15.1.2 If the ball is not in play when the time limit is reached, play shall resume with service by the player who received in the immediately preceding rally.
	<br><br>
	2.15.2 Thereafter, each player shall serve for 1 point in turn until the end of the game and if the receiving player or pair makes 13 returns the receiver shall score a point.
	<br><br>
	2.15.3 Once introduced, the system shall remain in operation until the end of the match.
</div>

</div>
{% endblock %}